server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: Amit@9696

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-service
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.value.default.type]": com.shopsphere.orderservice.dto.event.PaymentEvent
        "[spring.json.trusted.packages]": com.shopsphere.orderservice.dto.event
        "[spring.json.use.type.headers]": false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        "[spring.json.add.type.headers]": false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

    circuitbreaker:
      resilience4j:
        disable-time-limiter: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      InventoryClientreserveStockLongStockReservationRequest:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

retry:
  instances:
    inventoryReservationRetry:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions:
        - com.shopsphere.orderservice.exception.InventoryServiceUnavailableException

jwt:
  secret: gIwzftaZLAtQbMsCROtusFXFULfPKpR+XGNQk8xf1i0=
  expiration: 900000
  refresh-expiration: 604800000


